### ISSUE TITLE
TYPO: The sandbox Page 12

### ISSUE THREAD

**Issue by quickliketurtle** [Servers-for-Hackers/the-book#11]
Missing word on line: 
• vim - The timeless editor. Pro-Tip: Hit “esc” then type “:q” then hit

I think the word is 'enter'.

**Comment by fideloper** [comment]
lol, "GOOD LUCK!"

Thanks for pointing this out!

**Comment by fideloper** [comment]
Ah, I see - I used `<enter>` which the parser mistook for an HTML tag.
