### ISSUE TITLE
DNS Confusion

### ISSUE THREAD

**Issue by quickliketurtle** [Servers-for-Hackers/the-book#12]
Hey Looking at the DNS section page 66-67.

I'm a little confused by how this is worded. 
DNS is Domain Name Service, not Domain Name Servers. 
Instead of DN for name servers you should use NS.

Here is the related text.
This is the job of DNS (Domain Name Servers)
...
You can set the DN Servers
(ns1.somehost.com for example) to those of another service of your choice. 

Of course it may just be me... :-)

**Comment by fideloper** [comment]
I did mix that up a bit, I'll try to clear it up.

Thanks for the feedback!

**Comment by fideloper** [comment]
Cleaned up for next SFH book release, coming very soon. Thanks!
