### ISSUE TITLE
Question about the Beanstalkd  config in the case study

### ISSUE THREAD

**Issue by abshammeri** [Servers-for-Hackers/the-book#14]
In the case study that called "Queues & Workers" , page 48 , Beanstalkd IP has been changed to 0.0.0.0 instead of 127.0.0.1 , why is that ?
I expected  something like nginx/apache server , where they just listen to the localhost 127.0.01? what's the difference with Beanstalkd?

![screen shot 2014-10-08 at 9 42 45 am](https://cloud.githubusercontent.com/assets/815055/4554944/a6d4eae0-4eb6-11e4-9592-a45352e27327.png)

Thanks

**Comment by fideloper** [comment]
I'll try to clear that up in the case study. Thanks for the feedback!

In this case, Beanstalkd is running on a separate server from the application which makes new jobs. The application needs to communicate with Beanstalkd to create a new job.
- Server A: Laravel Application
- Server B: Beanstalkd

If Beanstalkd was listening on only localhost network (`127.0.0.1`), the laravel application would not be able to reach it. Beanstalkd can't receive communication from external servers if it's only listening on localhost!

So we set Beanstalkd to listen for connections on **all** networks by setting Beanstalkd to listen on `0.0.0.0`. Only then can the application (on server A) communicate with Beanstalkd (on server B).

If you run the `ifconfig` command, you'll see a list of all networks the server has. One is called `lo`, which is localhost. There is likely to be another called `eth0`, `eth1` and similar. These are other networks (network interfaces) the server can listen on.

> I should note that a  bunch of this is covered in the book. The case studies are more useful after reading the book as they gloss over some of the background information you may need. They assume most of it is covered in the book.
