### ISSUE TITLE
Duplicate content on page 49 Package Manager Apt Examples

### ISSUE THREAD

**Issue by sandrokeil** [Servers-for-Hackers/the-book#15]
There is duplicated content on page 49 of package manager apt examples with slightly different format:

Searching around the web, we see one repository from the popular Chris Lea for redis-server¹². We
can see that version 2.8.12 available! Let’s add this repository in to get the newer version of Redis:

Searching around the web, we can find the redis repository from Chris Lea¹³. This repository has
version 2.8.12 available!
Let’s add this repository in to get the newer version of Redis:

**Comment by fideloper** [comment]
Thanks! Where's the other place this is found? If I remember right, it
might be in a getting started section, perhaps with Vagrant?

**Comment by sandrokeil** [comment]
It's on the same page (page 49) of my pdf version downloaded from gumroad.com.

**Comment by fideloper** [comment]
Gotcha, thanks!

**Comment by fideloper** [comment]
Thanks! This change will be included in the next book update.
