### ISSUE TITLE
Duplicated Chapter "DNS & Hosts File"

### ISSUE THREAD

**Issue by sandrokeil** [Servers-for-Hackers/the-book#18]
The Chapter "DNS & Hosts File" under "Webservers" is defined on page 68-74 and page 149-155. The second one is between chapter "PHP" and "Server Setup for Multi-Tenancy Apps"

Found in pdf version downloaded from gumroad.com.

**Comment by fideloper** [comment]
Thanks! Removed the duplicate, to get pushed out with the next update. The first mention of it has been edited more thoroughly and is the "better" one.
