### ISSUE TITLE
Style - Ubuntu 14.04 not "fresh" any longer

### ISSUE THREAD

**Issue by minthemiddle** [Servers-for-Hackers/the-book#19]
This remark is just a matter of style. On page 2 you write "As of this writing. 14.04 LTS is freshly released." -- Well, your book was published in October, 14.04. was released in April. Maybe you wrote that paragraph back in May, but still "fresh" seems a bit out of line. I would just delete that information or substitute with "was released in April 14".

**Comment by fideloper** [comment]
Good point. I've removed that mention and the Vagrant chapter and added the updated version (doesn't mention if it's "fresh" to the Intro, which discusses Ubuntu versions.

This will be incorporated into the next update.
