### ISSUE TITLE
SSL chapter, nginx root not pointing to example.com

### ISSUE THREAD

**Issue by juukie** [Servers-for-Hackers/the-book#20]
On page 172 of the SSL chapter
![schermafbeelding 2014-10-14 om 16 07 54](https://cloud.githubusercontent.com/assets/2678657/4630297/5a2e1b9e-53ac-11e4-867d-3f340a5ffbff.jpg)

The first two scripts show `root /var/www/example.com;`.
The third has `root /var/www;`

**Comment by fideloper** [comment]
Thanks, I'll include this update along with some that I made yesterday.

Appreciate it!
