### ISSUE TITLE
It isn't it's, it's its

### ISSUE THREAD

**Issue by lumpysimon** [Servers-for-Hackers/the-book#22]
Some very pedantic typos for you!

In each of these cases "it's" should be "its":
- Page iv: "opinions about Linux and it's use"
- Page 8: "It's output"
- Page 9: "The server also has it's own private network"
- Page 16: "It's location on your computer"
- Page 17: "Vim as it's editor"
- Page 111: "will have it's own user"
- Page 111: "PHP-FPM has it's own user"
- Page 125: "any of it's subdomains"
- Page 183: "One of it's other popular uses"
- Page 233: "It's last commit"
- Page 277: "It's use has been hotly contested"
- Page 280: "It's excellent documentation"
- Page 286: "It's documentation is found"
- Page 288: "use Python in it's own environment"

**Comment by fideloper** [comment]
Pedantic are the best kind! Thanks, I'll get these added and pushed out
with the next update.

**Comment by fideloper** [comment]
These are now updated in the manuscript - the next book update will incorporate these.
