### ISSUE TITLE
Formatting / Readability - P.247

### ISSUE THREAD

**Issue by quickliketurtle** [Servers-for-Hackers/the-book#27]
Hello - 
on page 247 the following: 
Role directory structure
1 rolename
2 - files
3 - handlers
4 - meta
5 - templates
6 - tasks
7 - vars

Since this is surrounded by yml examples it is not immediately obvious this is a list of directories. Instead of '-' a '/' would make it more readable. 

rolename
  /files
  /handlers
etc... 

I was looking for this info specifically and scrolled past it a few times. :-)

**Comment by fideloper** [comment]
Thanks I'll take a look at that!

**Comment by fideloper** [comment]
Updated formats for tomorrows update!
