### ISSUE TITLE
AH00526: Syntax error on line 13 of /etc/apache2/sites-enabled/002-flaskapp.conf - Case study page 37 

### ISSUE THREAD

**Issue by anhvngo** [Servers-for-Hackers/the-book#29]
Error with apache2 running uWSGI:

```
<VirtualHost *:80>
ServerName example.com ServerAlias www.example.com
    DocumentRoot /var/www/example.com/public
<Directory /var/www/example.com/public>
Options -Indexes +FollowSymLinks +MultiViews AllowOverride All
Require all granted
<Proxy *>
Require all granted
```

error:

```
AH00526: Syntax error on line 13 of /etc/apache2/sites-enabled/002-flaskapp.conf:
<Proxy not allowed here
Action 'start' failed.
```

**Comment by fideloper** [comment]
I tried reformatting that with code brackets, since GH's markdown turned the apache tags into HTML tags.

It looks like Apache doesn't like `<Proxy>` inside of a `<Directory /var/www/example.com/public>` block?

**Comment by fideloper** [comment]
Also, can you make sure you're on a newer version of Apache? What version are you testing with? I'm fairly certain I tested all of these when writing the section, but it's definitely possible I missed something.

Thanks!

**Comment by anhvngo** [comment]
Server version: Apache/2.4.10 (Ubuntu)
Server built:   Jul 22 2014 22:45:03
yep it looks like Apache doesn't like <Proxy> inside of a <Directory 
Something should I change ? I am still not running it yet

**Comment by fideloper** [comment]
OK, looks like _all_ of those need to be moved outside of the `Directory` block!

```
<VirtualHost *:80>
    ServerName example.com
    ServerAlias www.example.com
    ServerAlias example.*.xip.io

    DocumentRoot /var/www/example.com/public

    <Directory /var/www/example.com/public>
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
    </Directory>

    <Proxy *>
        Require all granted
    </Proxy>
    <Location />
        ProxyPass uwsgi://127.0.0.1:9000/
        ProxyPassReverse uwsgi://127.0.0.1:9000/
    </Location>
    <Location /static>
        ProxyPass !
    </Location>

    ErrorLog ${APACHE_LOG_DIR}/example.com-error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog ${APACHE_LOG_DIR}/example.com-access.log combined

</VirtualHost>
```

**Comment by fideloper** [comment]
Man, that's ridiculous! I tested all of these when I wrote them - I must have moved those into the Directory block in a mass-edit after the fact :/

I re-tested all of these and updated the manuscript for my next update to get published.

Thanks so much for pointing this out to me! I appreciate it!
