### ISSUE TITLE
A few iptables issues

### ISSUE THREAD

**Issue by hostep** [Servers-for-Hackers/the-book#30]
Hi

I noticed a couple of problems in the iptables section.
1. On page 34 of the pdf, you speak about `iptables-persistant` twice, but it should be `iptables-persistent`
2. On page 33 & 36, the command `sudo iptables-save > /etc/iptables/rules.v4` doesn't work over here, I get a `-bash: /etc/iptables/rules.v4: Permission denied` message. I think it is because the sudo only works on the `iptables-save` command and not on the writing to the file. It should be possible to do it using a [sub-shell](http://superuser.com/a/54829), but I prefer the `sudo service iptables-persistent save` you mentioned on page 34

**Comment by fideloper** [comment]
Thanks!

I'll update that command to:

``` shell
sudo iptables-save | sudo tee /etc/iptables/rules.v4
```

...which should work there.

I must have been user `root` when testing that.

I appreciate the feedback/tweaks! Keep'em coming as you see them!
