### ISSUE TITLE
Small typo in fail2ban section

### ISSUE THREAD

**Issue by hostep** [Servers-for-Hackers/the-book#31]
Hi

On page 39 in the first paragraph underneath the 'Configuration' heading, you say:
`Open up the /etc/Fail2Ban/jail.conf file`

But it should be the local file (also all lowercase letters):
`Open up the /etc/fail2ban/jail.local file`

**Comment by fideloper** [comment]
Thanks! I've updated the manuscript for when I push up the next update.
