### ISSUE TITLE
Few issues in Apache chapter

### ISSUE THREAD

**Issue by hostep** [Servers-for-Hackers/the-book#32]
Hi again,
I found a few little issues in the Apache chapter:
1. Typo on page 103: `php5-fom`, should be `php5-fpm`
2. Typo on page 117: `operatinv system` should be `operating system`
3. Page 116: When I installed apache 2.4.10 using ppa:ondrej/apache2, it was installed with mpm-event enabled by default, not with mpm-prefork, maybe you should update the text a bit to reflect this?
4. Page 119, MPM Configuration heading, You say that the mpm configuration resides in the envvars file, but this isn't correct in my setup, the configuration resides in the /etc/apache2/mods-available/mpm_*.conf files

**Comment by fideloper** [comment]
Thanks, I'll take a look at those to update for the latest!

**Comment by fideloper** [comment]
Typos here are fixed. I'll check on items 3 and 4 still. I think envvars might be a secondary place for global or default MPM configurations.

**Comment by fideloper** [comment]
Confirmed, `mpm_event` installed with Ondrej package, until libapache2-mod-php5 is installed, which switches it to pre-fork automatically.

I see the same with ennvars as well.

Updating the book, thanks!
