### ISSUE TITLE
Typo in Vagrant section - Missing "for"

### ISSUE THREAD

**Issue by ivarb** [Servers-for-Hackers/the-book#33]
Hi @fideloper ,

First of all, great book so far!

I think there's a small typo on page 10 (PDF) within the section about the network interfaces. 

My guess is 
    "You’ll always see a loopback interface. You’ll usually see an internal network, useful servers within
a local network such as a data center." 

should become:
    "You’ll always see a loopback interface. You’ll usually see an internal network, useful **for** servers within a local network such as a data center."

**Comment by fideloper** [comment]
Thanks! I'll get these fixed up for the next book update.

**Comment by ivarb** [comment]
:+1:

**Comment by fideloper** [comment]
all set!
