### ISSUE TITLE
Typo on p.27 in iptables section under "Setting up Firewall" (duplicate "other")

### ISSUE THREAD

**Issue by ivarb** [Servers-for-Hackers/the-book#34]
Hi,

The instruction reads 
    "TARGET: What to do with the traffic and/or **other** other chains of rules to test traffic against" 

and I guess should be
    "TARGET: What to do with the traffic and/or other chains of rules to test traffic against"

**Comment by fideloper** [comment]
Fixed!

**Comment by ivarb** [comment]
Great!
