### ISSUE TITLE
What's the different between the leanpub and the one provided by your site?

### ISSUE THREAD

**Issue by waitingkuo** [Servers-for-Hackers/the-book#36]
I've bought the full package from Leanpub. It's seems that I need to download the whole video package again ( > 1G) if there's any update. I wonder is it more convenient to buy from your site? 
Do you provide a site that I can login and then the video on-line directly?

Your book is awesome! Thanks~~

**Comment by fideloper** [comment]
Buying from the site is via Gumroad, which I believe separates them out to multiple files for you. If you want, use coupon code "for-waitingkuo" to get it for free here: https://gumroad.com/l/sfh-cs-videos (that coupon will only work once).

Let me know if that doesn't let you download them individually. Both Gumroad and Leanpub get updates.

**Comment by waitingkuo** [comment]
It seems that i still download the whole zip file directly.

![screen shot 2015-01-11 at 1 06 50 am](https://cloud.githubusercontent.com/assets/1100923/5692375/43c44e06-992e-11e4-9d9f-297943e72ee2.png)

**Comment by fideloper** [comment]
Ah right you'll need to download the videos separately.

Don't be too worried though, I have some chapter updates planned but no
videos yet. Video updates (new videos) will be less common.

I don't have a way of putting them individually currently - sorry!

**Comment by waitingkuo** [comment]
It's ok~
I just finished your books and videos. Thank you for the contents and look forward to your new chapters!
