### ISSUE TITLE
SSL with Sha256

### ISSUE THREAD

**Issue by Garbee** [Servers-for-Hackers/the-book#37]
You may want to update the SSL cert generation stuff with the genrsa and req commands to have the `-sha256` flag so Chrome doesn't flag new ones as possibly insecure (since the current default generation is SHA1.

**Comment by fideloper** [comment]
Thank you! I'll check that.

**Comment by fideloper** [comment]
So if I'm reading this right, this is "transparent" in a production setting
where you are purchasing a certificate, as you aren't generated the
certificates, just the CSR.

However for self-signed, or if using an internal CA, this would become
important. That sound accurate?

**Comment by Garbee** [comment]
I'm not 100% sure tbh. I have always just self-generated my keys and then a CSR to get startssl to sign. If you use a web UI provided by your CA to generate the certificate then it should be a pretty simple task to select SHA256 in the dropdown (which should now be default.)

Self-signed it isn't even an issue since you are going to be bitched at in the first place for that. Weaker security shouldn't matter too much there. However this is "yet another thing" that would make the certificate weak. 

I also just realized in reconfiguring my setup that with StartSSL I _also_ need to make sure I download their SHA256 hashed PEMs. If I use the defaults they provide then I get a warning about the CA being SHA1 too. So that could also be another thing to note for others (making sure the entire chain is SHA256 or better.)

---

## Base Point: Certs be hard.

**Comment by fideloper** [comment]
Gotcha! I was confusing generating the private key with the cert itself.

Interestingly I've created private keys using the book method, and the
shaaaaaaaaaaa.com (or however many a's :P) say is using sha2

So overall not sure, but definitely worth a mention.

Thanks!

**Comment by Garbee** [comment]
Might be the version of openssl in use. I am on 14.04 now compared to 12.04 (or earlier?) before. So the default method could have changed or my old cert is simply being complained about due to my CA certificates... Let me actually go setup the SHA2 ones on my current production server and see.

**Comment by fideloper** [comment]
Cool - thanks for your time on that! (I've been using 14.04, so that could
be exactly what's going on)

**Comment by Garbee** [comment]
So it seems it is a change in the default of the newer OpenSSL versions. My original key (now expired) was SHA1 but the one I generated last year was SHA2 by default (FANTASTIC!). Just updated the CA PEM files being served to SHA2 ones and now I'm getting full green in Chrome.

So, maybe just drop a note in for readers to be sure their entire certificate chain uses the same hashing algorithm (SHA256 is default now) to avoid potential issues with Chrome since they are sunsetting SHA1 starting now.

Either way, seems like now that SHA2 is the default (which I thought was not the case before) I'll close this issue out. A note on the full chain would simply be nice for people to know to check up on their CA hashes.

**Comment by fideloper** [comment]
I'm gonna keep this open so I remember to add a note when I push out the next update. Thanks a lot of your time checking up on it! :beers:
