### ISSUE TITLE
Typo in Security Chapter section Making Our User a Super User

### ISSUE THREAD

**Issue by uxweb** [Servers-for-Hackers/the-book#4]
I found a typo related to this paragraph on page 17 of the PDF edition:

"The use if % signifies a group name instead of a username. After saving and exiting, we can assign
group “sudo” to our new user and they’ll also have sudo abilities:"

Where the "The use if %" should be "The use of %".

Thanks!

**Comment by fideloper** [comment]
Thank you!

**Comment by fideloper** [comment]
This change will be included in the next book update.
