### ISSUE TITLE
Can the book buyers access the new videos?

### ISSUE THREAD

**Issue by waitingkuo** [Servers-for-Hackers/the-book#40]
Hi

it seems that there are more videos provided in your site now but not open yet
Will the original buyer can access those new awesome videos? or we have to pay more?
thanks

(i bought the full package books, case studies, & and videos)

THanks

**Comment by fideloper** [comment]
Hello!

The site includes some videos that are in the book, however the site will
be a subscription based payment. I'm going to be providing many, many more
videos, which I think will be well worth it!

**Comment by waitingkuo** [comment]
Thanks~
Look forward to it
