### ISSUE TITLE
Typo with the command for install php-fpm

### ISSUE THREAD

**Issue by frankperez87** [Servers-for-Hackers/the-book#41]
On page 103 where you discuss FilesMatch I noticed that the line where you install the php5-fpm package has a typo. 

Currently: 
# Install PHP-FPM if necessary:

sudo apt-get install -y **php5-fom**

Should be:
# Install PHP-FPM if necessary:

sudo apt-get install -y **php5-fpm**

**Comment by hostep** [comment]
This is a duplicate of https://github.com/Servers-for-Hackers/the-book/issues/32 ;)
