### ISSUE TITLE
Typo on Introduction

### ISSUE THREAD

**Issue by devdrops** [Servers-for-Hackers/the-book#45]
Found in the .mobi version.

At the "Introduction - The Sandbox - Install VirtualBox and Vagrant" section.

The word "Installing" is missing the 's'.

A screenshot can be found in the link above:
https://www.evernote.com/shard/s152/sh/054b4ca3-69e9-42bc-bc11-a888660615c7/47080aa0f1c22972baa3fde6ecd4baac

**Comment by fideloper** [comment]
Fixed for next release, thanks!
