### ISSUE TITLE
Typo in "The Sandbox": an to a

### ISSUE THREAD

**Issue by weerd** [Servers-for-Hackers/the-book#47]
#### Section:

The Sandbox
#### Context:

**from:**
I like to get around this potential problem by assigning an private-network IP address to my Vagrant server.

**to:**
I like to get around this potential problem by assigning a private-network IP address to my Vagrant server.

**Comment by fideloper** [comment]
Thanks again! Updated for next release.

**Comment by weerd** [comment]
Sure thing! :+1:
