### ISSUE TITLE
"https://book.serversforhackers.com/#dlpreview" doesn't actually download/send preview

### ISSUE THREAD

**Issue by jzohrab** [Servers-for-Hackers/the-book#48]
Clicking the link takes me to a sign-up form, but I'd already signed up.  I filled in the form again and it said the email was already taken.  There's no "download" link displayed, and I didn't receive an email.  Checked spam folder.

**Comment by fideloper** [comment]
Hey, did you end up finding the preview? I know mailchimp (the system automating that in the background) can be slow to send those out sometimes.

**Comment by fideloper** [comment]
I found the direct link to that: https://s3.amazonaws.com/sfh-assets/serversforhackers-preview.zip

**Comment by jzohrab** [comment]
Thanks Chris.  The page logic is still screwy, you might want to look into that.  It was a confusing user experience.
