### ISSUE TITLE
Typo in "The Sandbox": current to currently

### ISSUE THREAD

**Issue by weerd** [Servers-for-Hackers/the-book#49]
#### Section:

The Sandbox
#### Context:

**from:**
The "working directory" is the directory you are current in.

**to:**
The "working directory" is the directory you are currently in.

_might not be a typo_ :shrug:

**Comment by fideloper** [comment]
Looks like I fixed this a while ago but forgot to close the issue 💃 
Thanks!

**Comment by weerd** [comment]
No worries 💃 Looking forward to reading v2 with the new updates! Also, enjoyed your presentation at Laracon!
