### ISSUE TITLE
Typo in Security Chapter section Creating a Local SSH Key

### ISSUE THREAD

**Issue by uxweb** [Servers-for-Hackers/the-book#5]
I found a small typo in page 24 of the PDF edition.

"While creating an SSH key, you will ask you for a password! You can either leave this blank (for
passwordless access) or enter in a password."

Where "you will ask you for a password!" think should be "it will ask you for a password!".

Hope this helps! :D Thanks.

**Comment by fideloper** [comment]
Thanks! Definitely a huge help!

**Comment by fideloper** [comment]
This change will be included in the next book update.
