### ISSUE TITLE
ubuntu/xenial64 doesn't contain /vagrant

### ISSUE THREAD

**Issue by jhoopes** [Servers-for-Hackers/the-book#51]
Hi,

Going through the book for 16.04, and the vagrant box doesn't contain the virtual box guest additions, and so the file syncing doesn't work out of the box.

After going in and running

```
sudo apt-get update
sudo apt-get install virtualbox-guest-utils
```

exiting, halting the machine, and adding the explicit shared folder of:

```
config.vm.synced_folder ".", "/vagrant"
```

and then running

```
vagrant up --provision
```

The shared folders then work as expected.  Seems to be a bug with the base box:
https://bugs.launchpad.net/cloud-images/+bug/1565985

**Comment by fideloper** [comment]
Thank you I'll check that out! Havent run into that, but I'll bet I've
since used a different underlying box.

**Comment by fideloper** [comment]
The book is now updated to use the [bento/ubuntu-16.04](https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04) box, which is one I've found that seems trust worthy, popular, and most importantly, actually works!

**Comment by fideloper** [comment]
(Book release made today has that update)
