### ISSUE TITLE
UPDATE: where is it?

### ISSUE THREAD

**Issue by markljackson** [Servers-for-Hackers/the-book#52]
1. I've not received an update email, as promised.
2. The "customer service" email (serversforhackers@helpful.io) account BOUNCES, so I'm unable to contact the site owner.

Any chance he comes here?

**Comment by fideloper** [comment]
He does!

Leanpub and I think gumroad both have had real deliverability issues...

But anyway, you'll don't need the email you get updates, just need to go
back to where you purchased it from!

Usually that's gumroad or leanpub, bit could be Mijingo or, of bought via
StackSocial, store.serversforhackers.com.

If you remember where it was purchased, that'll help me find you (although
only gumroad gives me the ability to find my customers on an email search
:/)

**Comment by markljackson** [comment]
_lol_

Thanks for the email. We figured that out last night. Logged in, and pulled the goodies.

Thanks for the response. Time for some Mi Tierra!
