### ISSUE TITLE
Broken link to Rackspace in Introduction

### ISSUE THREAD

**Issue by andyroodee** [Servers-for-Hackers/the-book#54]
The link in the following text points to a Rackspace url that no longer exists:

"I recommend this Rackspace knowledge-base article for more information on the various Linux
distributions: http://www.rackspace.com/knowledge_center/article/choosing-a-linux-distribution"

It appears to have been moved here: https://community.rackspace.com/products/f/25/t/6677

**Comment by fideloper** [comment]
Fixed for next release - thank you very much for finding the relevant Rackspace link as well!
