### ISSUE TITLE
Typo in Introduction Chapter section Linux Distributions

### ISSUE THREAD

**Issue by uxweb** [Servers-for-Hackers/the-book#6]
Hi, I found a small typo on page IV of the PDF edition.

"As major versions are released yearly, only every other major release of Ubuntu us an LTS".

Where "Ubuntu us an LTS" i think should be "Ubuntu is an LTS".

Thanks!

**Comment by fideloper** [comment]
Thank you!

**Comment by fideloper** [comment]
Thanks! This change will be included in the next book update.
