### ISSUE TITLE
iptables-persistent service name change Page 33

### ISSUE THREAD

**Issue by bmcd** [Servers-for-Hackers/the-book#66]
It seems like the iptables-persistent service has a new name. Should be:

`sudo service netfilter-persistent start`

**Comment by fideloper** [comment]
Thanks, I'll get that updated!

**Comment by rnottinger** [comment]
if iptables-persistent and netfilter-persistent are both installed then you can save iptable rules by running 
netfilter-persistent save
which will create the files /etc/iptables/rules.v4 & /etc/iptables/rules.v6
https://askubuntu.com/questions/911863/where-does-netfilter-persistent-save-the-iptables-rules

also to prevent the dialog from asking if you want to save rules when you install iptables-persistent ...
DEBIAN_FRONTEND=noninteractive apt install -y iptables-persistent

**Comment by fideloper** [comment]
Thanks!

**Comment by fideloper** [comment]
Updated for next release
