### ISSUE TITLE
File Sharing wasn't on by default

### ISSUE THREAD

**Issue by kyleridolfo** [Servers-for-Hackers/the-book#7]
Hi! Under File Sharing (first section), it says “Vagrant sets up file sharing for you.” However, after following all of the instructions to this point I noticed it wasn't. I was able to figure this out with a bit of Googling but thought I would mention it in case some readers are stuck.

I only had to modify the Vagrantfile to include:
config.vm.synced_folder "~/Sites/sfh", "/vagrant"

**Comment by fideloper** [comment]
Oh? It should default as if the following were set:

``` ruby
config.vm.synced_folder ".", "/vagrant"
```

But I can add that in there if that's not true any longer.

Thank you!

**Comment by fideloper** [comment]
I've updated the book to show this default configuration in the File Sharing section.

Thanks
