### ISSUE TITLE
UFW Delete Rules section p. 39

### ISSUE THREAD

**Issue by alexkart** [Servers-for-Hackers/the-book#71]
```
# Stop accepting https traffic:
sudo ufw delete deny 443/tcp
```

I think comment or command is wrong, should be 

```
# Stop accepting https traffic:
sudo ufw delete allow 443/tcp
```

or 

```
# Delete the rule which denies https traffic:
sudo ufw delete deny 443/tcp
```

**Comment by Alienpruts** [comment]
I can attest to that :)

However : executing sudo ufw delete allow 443/tcp gives the following result :

'Could not delete non-existent rule
Could not delete non-existent rule (v6)'

**Comment by fideloper** [comment]
Updated, thanks
