### ISSUE TITLE
P 54 : ppa:rwky/redis is deprecated

### ISSUE THREAD

**Issue by Alienpruts** [Servers-for-Hackers/the-book#74]
The PPA notes have this to say:

'This ppa is no longer maintained. Please consider https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server instead'

Perhaps remove the line from the book, or mention it is deprecated?

**Comment by fideloper** [comment]
Will do, thanks!

**Comment by fideloper** [comment]
Updated for next release
