### ISSUE TITLE
P54 : ElasticSearch installation link returs 404

### ISSUE THREAD

**Issue by Alienpruts** [Servers-for-Hackers/the-book#75]
Link was : https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

I could not find another installation url, however, I did find this:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-16-04

but in that article they download .deb packages to install ElasticSearch, so perhaps this cannot be used?

**Comment by fideloper** [comment]
Updated for latest (v6 of elasticsearch) from their newer install docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
