### ISSUE TITLE
Typo (page 180, Creating Self-Signed SSLs): "...you can click passed that..."

### ISSUE THREAD

**Issue by philibusted** [Servers-for-Hackers/the-book#77]
> Your browsers will initially give you a warning for using an un-trusted certificate, but you can click **passed** that and test your web application with your own SSL certificate.

The bolded word should be changed to **past**, I believe. (Not to sound pretentiously didactic!)

(FWIW, I also glanced and tried to filter through the other issues comments to see if this had been mentioned; but there's every chance I may have failed; so apologies if this is extraneous!)

**Comment by fideloper** [comment]
Thanks, appreciate it!

**Comment by fideloper** [comment]
Thanks, updated for next release 👍
