### ISSUE TITLE
SSH Config

### ISSUE THREAD

**Issue by gadam** [Servers-for-Hackers/the-book#78]
Hi @fideloper 
Thanks for a great resource.  

I found the SSH chapter particularly helpful.  I think the following tip may be useful for your macOS users.  Adding the line ```UseKeychain yes``` to the ssh config file for keys created with passphrases will store the key's passphrase in macOS' keychain and then the user no longer needs to type the passphrase for that host on subsequent attempts to connect via ssh.

**Comment by fideloper** [comment]
Thanks! Yea that's relatively new that it's needed, I'll make a note on
that.

Thanks!
