### ISSUE TITLE
Typo: Page 236 (PDF)

### ISSUE THREAD

**Issue by lorenzodalaqua** [Servers-for-Hackers/the-book#79]
In the third paragraph explaining _proxy_cache_key_, on page 236:

>  Cookies do affect caching, so be careful of your treatment with them! You may accidentally end up
> with a file being cached in duplicate per **indivisual** cookie (effectively per site visitor).

I believe you meant _individual_ cookie. 

Great work on the book by the way!

**Comment by fideloper** [comment]
Updated for next release - thanks!
