### ISSUE TITLE
Typo in Security Chapter section Setting Up the Firewall: Iptables

### ISSUE THREAD

**Issue by uxweb** [Servers-for-Hackers/the-book#8]
I found a small typo in page 27 of the PDF edition.

"The following is basic list of INPUT (inbound) rules we’ll be building in this chapter:"

Where "The following is basic list of INPUT" think should be "The following is a basic list of INPUT".

Thanks :).

**Comment by fideloper** [comment]
thanks as always, super appreciative of your help!

**Comment by fideloper** [comment]
Thanks! This change will be included in the next book update.
