### ISSUE TITLE
Flushing tables before enabling ufw page 37

### ISSUE THREAD

**Issue by bmcd** [Servers-for-Hackers/the-book#80]
You recommend flushing existing iptables rules before running `sudo ufw enable` if it's not a fresh install. If you were following along and also set the default policy on INPUT and FORWARD to DROP, when you enable ufw it seems to block all incoming connections. Maybe add commands for resetting those to ACCEPT to the flush commands in that section.

**Comment by fideloper** [comment]
Gotcha, good idea - thanks!

**Comment by fideloper** [comment]
Updated for next release
