### ISSUE TITLE
Typo @ Page 50 Section - "New in 16.04 (Xenial)"

### ISSUE THREAD

**Issue by philibusted** [Servers-for-Hackers/the-book#82]
> Where we once used apt-get install, we now use apt install. Where we once used apt-cache
show, we __not__ use apt show. I’ve updated __the below__ to show the combined usage where appropriate.

What I assume you meant :) =>

Where we once used apt-get install, we now use apt install. Where we once used apt-cache
show, we __now__ use apt show. I’ve updated __the examples below__ to show the combined usage where appropriate.

**Comment by fideloper** [comment]
Yep, thanks!!

**Comment by fideloper** [comment]
Updated for next release
