### ISSUE TITLE
Page 111: Apache with FastCGI (unix socket)

### ISSUE THREAD

**Issue by ltanase77** [Servers-for-Hackers/the-book#86]
Hi,
Chapter: **Webservers**
Section:  _Apache - Apache and Web Application - Apache with FastCGI_ (page 111 of pdf version)  

When explaining using  FilesMatch Handler with Unix socket, the line:
`SetHandler "proxy:unix:/var/run/php5-fpm.sock|fcgi:"`
 is missing at the end //localhost/ as per Apache documentation [https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html](url).

I have tried using the line in the book but gives a _file not found error_. It worked fine once I have added the //localhost/ at the end of the line, as follows: `SetHandler "proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost/"`

**Comment by fideloper** [comment]
Thanks, I'll get that updated! I wonder if that's something I missed in the update to Apache 2.4.

**Comment by fideloper** [comment]
Updated for next release
