### ISSUE TITLE
Hi Chris, is your ebook updated?

### ISSUE THREAD

**Issue by YaoCabrera** [Servers-for-Hackers/the-book#87]
Hi, Chris.

I found your website looking for information about web servers and I found your book in LEANPUB.

I have seen that users have made several questions and corrections, but LEANPUB says that your book is not updated since 2016. So I prefer to ask you **when was the last time the book was updated?** 

Thanks for your attention.

**Comment by fideloper** [comment]
Hi!

I don't remember! The last major update was in July 2016, and the next
major update will be this year soon after Ubuntu 18.04 is released. I'll
include a lot of user's updates that I haven't gotten to yet then as well.
(The last minor update with user's updates from his repository was likely
in mid-2017).

- Chris
