### ISSUE TITLE
Download videos

### ISSUE THREAD

**Issue by realmabs** [Servers-for-Hackers/the-book#88]
Hi,
I have somehow lost videos that were part of that book. Now tried to access page/link I had to download book/updates but this wasn't working. Couldn't find one on the book page also.
can you tell me page to download videos again?

**Comment by fideloper** [comment]
If you purchased on a Stack Exchange site, I can help you get a copy of the book elsewhere. The integration with their site is turned off now.  Shoot me an email at my username here [at] gmail.com and I'll get you sorted!
